2 and 3 tasks completed
js-tasks-ru/vue-20210810_poscan pull request #3
Opened 2021-08-22 16:47 UTC by Poscan

2021-08-22 16:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-22 18:31 UTC, ShGKme requested changes
Требуется исправление заголовка в 05-MeetupAgenda.

Можно сразу убрать лишние тернарные операторы из шаблонов.

2021-08-22 18:31 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click="$emit('update:count', count + 1)">{{count ? count : 0}}</button>`,
Проверка в шаблоне не нужна. Значение `count` по умолчанию 0 уже указано в параметрах через `default: 0`

2021-08-22 18:31 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/index.html
>          },
Обычно файл с примером использования компонента задачи не требуется редактировать.

2021-08-22 18:31 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +  template: `<p class="meetup-description">{{ description ? description : "" }}</p>`,
Аналогично CounterButton, здесь не требуется проверка. При отсутствии описания ничего выводиться не будет, и отдельно выводить ничего через `''` не требуется

2021-08-22 18:31 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +        <h1 class="meetup-cover__title">{{title}}</h1>
В текстовой интерполяции принято добавлять пробелы: `{{ title }}`. Сейчас в некоторых задачах у вас пробелы есть, а в некоторых нет.

2021-08-22 18:31 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +    },
Это вычисляемое свойство лишнее. Вычисляемое свойство вычисляется автоматически на основе реактивных данных. Объект `navigator` - не реактивный и никогда не изменяется. 

Это значение нужно только в `localeDate`, можно его там и вычислять.

2021-08-22 18:31 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +        <time :datetime="new Date(date).toISOString().substr(0, 10)">{{localeDate}}</time>
Значение у `datetime` получается довольно длинное. Лучше такие выражения вычислять в вычисляемом свойстве, чтобы не нагружать шаблон лишней логикой.

2021-08-22 18:31 UTC, ShGKme commented on 02-components/05-MeetupAgenda/MeetupAgendaItem.js
> +    },
Заголовок по умолчанию определяется типом пункта программы. Для registration это "Регистрация", для "opening" - Открытие. Это решение работает только с регистрацией для прохождения соответствующего теста и не пройдёт, если в тесте проверится другой тип.

Объект с заголовками пунктов программы по умолчанию аналогичен объекту с иконками.

2021-08-22 18:31 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), v-bind(imageUrl);
Отлично 👍

2021-08-23 13:08 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-23 14:11 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-08-23 14:12 UTC, merged